# Generated by Django 5.1.1 on 2024-10-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='countdowntime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
