# Generated by Django 5.1.1 on 2024-10-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_rename_country_city_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='City',
            new_name='city',
        ),
    ]
