# Generated by Django 5.1.1 on 2024-10-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_shippingrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingRate',
        ),
    ]
