# Generated by Django 5.0.4 on 2024-07-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_alter_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='image',
        ),
    ]
