# Generated by Django 5.0.4 on 2024-07-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_myuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Forgotpassword',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
