# Generated by Django 5.1 on 2024-08-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile'),
        ),
    ]
