# Generated by Django 5.1.1 on 2024-11-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0024_alter_forgotpassword_expires_at_uservisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forgotpassword',
        ),
    ]
