# Generated by Django 5.0.7 on 2024-09-13 10:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cart1_delete_cart'),
        ('Products', '0024_alter_category_c_id_alter_product_pcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart1',
            new_name='Cart',
        ),
    ]
