# Generated by Django 5.0.7 on 2024-09-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0012_order_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
