# Generated by Django 5.1.1 on 2024-10-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0014_shippingrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingRate',
        ),
    ]
