# Generated by Django 5.1.1 on 2024-10-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0017_remove_shippingrate_id_alter_shippingrate_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingRate',
        ),
    ]
