# Generated by Django 5.1.1 on 2024-10-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0019_shippingrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingRate',
        ),
    ]
