# Generated by Django 5.1.1 on 2024-11-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0021_shippingrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='shipping_address',
            name='address',
        ),
        migrations.AddField(
            model_name='shipping_address',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping_address',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping_address',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipping_address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipping_address',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
