# Generated by Django 5.1.1 on 2024-11-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0023_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={},
        ),
    ]
