# Generated by Django 5.1.1 on 2024-11-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0027_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
