# Generated by Django 5.1.1 on 2024-11-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0029_order_gst_order_shipping_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='delivered', max_length=20),
            preserve_default=False,
        ),
    ]
