# Generated by Django 5.1.1 on 2024-11-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0031_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
