# Generated by Django 5.0.4 on 2024-07-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='wJ', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='mgxD', max_length=5, unique=True),
        ),
    ]
