# Generated by Django 5.0.4 on 2024-07-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_category_c_id_alter_product_pcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='S2', max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='ESQ7', max_length=5, unique=True),
        ),
    ]
