# Generated by Django 5.0.4 on 2024-07-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_category_c_id_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/Image/category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='Qe', max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/Image/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='VPss', max_length=5, unique=True),
        ),
    ]
