# Generated by Django 5.0.4 on 2024-07-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_category_image_alter_category_c_id_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='vs', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='ZStq', max_length=5, unique=True),
        ),
    ]
