# Generated by Django 5.1 on 2024-08-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_rename_image_image_images_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='6z', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='1G5R', max_length=5, unique=True),
        ),
    ]
