# Generated by Django 5.1 on 2024-08-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_category_c_id_alter_product_pcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='gF', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='1UPR', max_length=5, unique=True),
        ),
    ]
