# Generated by Django 5.0.7 on 2024-08-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_category_c_id_alter_product_pcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='vd', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='ApUl', max_length=5, unique=True),
        ),
    ]
