# Generated by Django 5.0.7 on 2024-08-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_remove_product_old_price_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='wX', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='a1Mt', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='size',
            field=models.CharField(choices=[('0-6 months', '0-6 months'), ('6-12 months', '6-12 months'), ('1-2 years', '1-2 years'), ('2-3 years', '2-3 years'), ('3-4 years', '3-4 years'), ('4-5 years', '4-5 years'), ('5-6 years', '5-6 years'), ('6-7 years', '6-7 years'), ('7-8 years', '7-8 years'), ('8-9 years', '8-9 years'), ('9-10 years', '9-10 years'), ('10-11 years', '10-11 years'), ('11-12 years', '11-12 years')], max_length=50),
        ),
    ]
