# Generated by Django 5.1 on 2024-08-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_alter_category_c_id_alter_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='Zq', max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/category/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='D6Jm', max_length=5, unique=True),
        ),
    ]
