# Generated by Django 5.0.7 on 2024-09-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0035_contactme_alter_category_c_id_alter_product_pcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='WW', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='bqZj', max_length=10, unique=True),
        ),
    ]
