# Generated by Django 5.0.7 on 2024-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0040_alter_category_c_id_alter_product_pcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='T8', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='jUXh', max_length=10, unique=True),
        ),
    ]
