# Generated by Django 5.1.1 on 2024-10-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0058_delete_contactme_alter_category_c_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='21', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='5blH', max_length=10, unique=True),
        ),
    ]
