# Generated by Django 5.1.1 on 2024-11-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0073_alter_category_c_id_alter_product_pcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='shipping_box',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='tt', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='AFhx', max_length=10, unique=True),
        ),
    ]
