# Generated by Django 5.1.1 on 2024-11-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0074_productprice_shipping_box_alter_category_c_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='Cm', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='mybq', max_length=10, unique=True),
        ),
    ]
