# Generated by Django 5.1.1 on 2024-11-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0076_alter_category_c_id_alter_product_pcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='pl', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='RYn9', max_length=10, unique=True),
        ),
    ]
