# Generated by Django 5.1.1 on 2024-11-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0079_alter_category_c_id_alter_product_pcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='VZ', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='8BSR', max_length=10, unique=True),
        ),
    ]
