# Generated by Django 5.1.1 on 2024-11-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0084_alter_category_c_id_alter_product_pcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='dd', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='2SMV', max_length=10, unique=True),
        ),
    ]
