# Generated by Django 5.1.1 on 2024-11-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0086_category_is_active_alter_category_c_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='6e', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='1khx', max_length=10, unique=True),
        ),
    ]
