# Generated by Django 5.1.1 on 2024-11-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0087_alter_category_c_id_alter_product_pcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='category',
            name='c_id',
            field=models.CharField(default='je', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='pcode',
            field=models.CharField(default='pVOt', max_length=10, unique=True),
        ),
    ]
